W04 hh
gui2de/ppol768-spring23 pull request #137
Opened 2023-02-14 03:23 UTC by hill-hannah

2023-02-14 18:22 UTC, mikegiunti commented on Individual Assignments/Hill Hannah/week-04/wk04-hh.do
> +use "q1_village_pixel.dta", clear
Use the command use "01_data/q1_village_pixel.dta" to make sure you are using the right folder. You might also need a working directory change.

2023-02-14 18:24 UTC, mikegiunti commented on Individual Assignments/Hill Hannah/week-04/wk04-hh.do
> +replace pixel_consistent = 1 if payout == 0 & payout == 1
This might be a hard coded chunk

2023-02-14 18:25 UTC, mikegiunti commented on Individual Assignments/Hill Hannah/week-04/wk04-hh.do
> +bysort village: replace pixel_village = 1 if serial == hh_max & pixel_first != pixel_last
Better way to do this.
egen tag = tag(village pixel)
bysort village: gen pixel_village_alt = sum(tag)
bysort village: egen pix_vil_max = total(tag)
bysort village: replace pixel_village_alt = 0 if pix_vil_max == 1
bysort village: replace pixel_village_alt = 1 if pix_vil_max > 1

2023-02-14 18:27 UTC, mikegiunti commented on Individual Assignments/Hill Hannah/week-04/wk04-hh.do
> +forvalues i=1/135 {
This doesn't work for me

2023-02-14 18:29 UTC, mikegiunti commented on Individual Assignments/Hill Hannah/week-04/wk04-hh.do
> +replace average_stand_score = ((stand_r1_score + stand_r2_score +stand_r3_score)/3)
Normalizing a score might instead be making it a 0 to 1 scale. I did this after googling what it meant but I might be wrong.

2023-02-14 18:30 UTC, mikegiunti commented on Individual Assignments/Hill Hannah/week-04/wk04-hh.do
> +keep if j >= 2
I had to do this too :)

2023-02-14 18:31 UTC, mikegiunti commented on Individual Assignments/Hill Hannah/week-04/wk04-hh.do
> +// split grades //
This section, in general, could use a loop, but we haven't talked about them enough yet.

2023-02-14 18:33 UTC, mikegiunti requested changes
Please review comments I left.

2023-02-14 18:33 UTC, mikegiunti commented on Individual Assignments/Hill Hannah/week-04/README.md
> +
Write something funny here. It's always good to get some practice in markdown.

2023-02-14 18:33 UTC, mikegiunti commented on Individual Assignments/Hill Hannah/week-04/wk04-hh.do
> +// Hannah Hill //
I would try to run question 2 again and change up the copied and pasted code from the hint. You need to remove Ali's comments as they serve no purpose and can be summarized in a section separate from the code. It is likely that they are interfering with it running.

2023-02-21 04:15 UTC, hill-hannah commented on Individual Assignments/Hill Hannah/week-04/wk04-hh.do
> +bysort village: replace pixel_village = 1 if serial == hh_max & pixel_first != pixel_last
thank you! this was very helpful

2023-02-21 04:16 UTC, hill-hannah commented on Individual Assignments/Hill Hannah/week-04/wk04-hh.do
> +replace pixel_consistent = 1 if payout == 0 & payout == 1
yep, you're right. i recoded it using the min & max we discussed in class.

2023-03-14 16:47 UTC, closed without merging