Problem Set 2 Incomplete
gui2de/ppol768-spring23 pull request #190
Opened 2023-02-21 04:57 UTC by dnr36

2023-02-21 14:12 UTC, mikegiunti commented on Individual Assignments/Rivas Garcia Diana/week-05/PS2.do
> +
I am pretty sure that school code needs to be separated from the candidate number. Just use split id, parse("-")

2023-02-21 14:13 UTC, mikegiunti commented on Individual Assignments/Rivas Garcia Diana/week-05/PS2.do
> +
You need to add the methods you used to try and solve the problem. Hint: go check the discussion board with Ali's suggestions, he has a partial solution to this that requires a bit more work to completely solve the problem. If you can't understand what he is saying, reply to this comment and I will try to explain it better.

2023-02-21 14:19 UTC, mikegiunti commented on Individual Assignments/Rivas Garcia Diana/week-05/PS2.do
> +merge 1:m density using `"/Users/diana/Desktop/Github/ppol768-spring23/Class Materials/week-05/03_assignment/01_data/q2_CIV_Section_0.dta"'
Hint 2: once you have the population density per department. You will want to do a many to many merge.

2023-02-21 14:20 UTC, mikegiunti requested changes

2023-02-21 14:20 UTC, mikegiunti commented on Individual Assignments/Rivas Garcia Diana/week-05/PS2.do
> +
Please view my comments above. I can't be too exhaustive since I have my own work to do, but feel free to ask questions.

2023-03-09 17:19 UTC, mikegiunti approved these changes
Good Job! Everything works great! And I really like the code on the last question.

2023-03-10 17:28 UTC, dnr36 commented on Individual Assignments/Rivas Garcia Diana/week-05/PS2.do
> +
Thank you for comments!

2023-03-14 16:54 UTC, closed without merging