Updated README
gui2de/ppol768-spring23 pull request #77
Opened 2023-01-31 21:36 UTC by natespilka

Here are some pictures and an updated README.

2023-01-31 21:42 UTC, natespilka commented
It looks like some unwanted images were copied over. I'll remove them.

2023-01-31 22:19 UTC, mikegiunti requested changes

2023-01-31 22:19 UTC, mikegiunti commented on Individual Assignments/Spilka Nathaniel/week-02/README.md
> +$$ MSE = \frac{\sum_{i = 1}^{n}(y_{i}-\hat{y}_{i})^{2}}{n} $$
Everything looks good, but I would revise the math section. I am not super sure how you can do that and I can't preview my changes.

2023-01-31 23:00 UTC, natespilka commented on Individual Assignments/Spilka Nathaniel/week-02/README.md
> +$$ MSE = \frac{\sum_{i = 1}^{n}(y_{i}-\hat{y}_{i})^{2}}{n} $$
What about this section needs revision? 
Thanks for checking it out

2023-01-31 23:25 UTC, mikegiunti commented on Individual Assignments/Spilka Nathaniel/week-02/README.md
> +$$ MSE = \frac{\sum_{i = 1}^{n}(y_{i}-\hat{y}_{i})^{2}}{n} $$
When you preview the math, it seems that the Sum symbol is overlapping the i = 1 function. You can preview it by going to changes and pressing the document icon on the top right

2023-02-01 00:07 UTC, hill-hannah requested changes
profile picture now shows :) still can't see favorite place picture!

2023-02-01 02:58 UTC, natespilka commented
@mikegiunti and @hill-hannah it looks like it's good to go. Hannah stole my favorite place interestingly enough but it's a lovely place so I'll forgive her.

2023-02-01 03:02 UTC, hill-hannah approved these changes

2023-02-02 20:15 UTC, mikegiunti approved these changes

2023-02-02 20:19 UTC, merged

2023-02-02 20:24 UTC, natespilka commented
thanks!

2023-02-06 22:52 UTC, bbdaniels commented
Great work on this to all of you!